name: nordic_dfu
description: This library allows you to do a Device Firmware Update (DFU) of your nrf51 or nrf52 chip from Nordic Semiconductor. Fork of flutter-nordic-dfu.
version: 3.1.0
homepage: https://github.com/juliansteenbakker/nordic_dfu

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.steenbakker.nordicdfu
        pluginClass: NordicDfuPlugin
      ios:
        pluginClass: NordicDfuPlugin
